name: gamepads
description: A Flutter plugin to handle gamepad input across multiple platforms.
version: 0.1.7
homepage: https://github.com/flame-engine/gamepads
repository: https://github.com/flame-engine/gamepads/tree/main/packages/gamepads

flutter:
  plugin:
    platforms:
      android:
        default_package: gamepads_android
      ios:
        default_package: gamepads_ios
      linux:
        default_package: gamepads_linux
      macos:
        default_package: gamepads_darwin
      windows:
        default_package: gamepads_windows

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  gamepads_android:
    path: ../gamepads_android
  gamepads_darwin:
    path: ../gamepads_darwin
  gamepads_ios:
    path: ../gamepads_ios
  gamepads_linux:
    path: ../gamepads_linux
  gamepads_platform_interface:
    path: ../gamepads_platform_interface
  gamepads_windows:
    path: ../gamepads_windows

dev_dependencies:
  flame_lint: ^0.2.0
  flutter_test:
    sdk: flutter
